pipeline {
    agent { node { label 'AGENT-1' } }

    parameters {
        choice(name: 'environment', choices: ['dev', 'qa', 'prod'], description: 'Terraform environment folder / tfvars set')
        string(name: 'version', defaultValue: '1.0.0', description: 'Application version to deploy')
    }

    stages {
        stage('Deploy') {
            steps {
                echo "Deploying ..."
                echo "Version from Params : ${params.version}"
                echo "Environment from Params : ${params.environment}"
            }
        }

        stage('Init') {
            steps {
                dir('terraform') {
                    sh 'terraform init -reconfigure'
                }
            }
        }

        stage('Approve') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                echo "Hello, ${params.PERSON}, nice to meet you."
            }
        }

        stage('Plan') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'aws-creds',
                    usernameVariable: 'AWS_ACCESS_KEY_ID',
                    passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                )]) {
                    dir('terraform') {
                        sh """
                            export AWS_DEFAULT_REGION=ap-south-1
                            terraform plan \
                              -var-file=${params.environment}/${params.environment}.tfvars \
                              -var="app_version=${params.version}" \
                              -var="env=${params.environment}"
                        """
                    }
                }
            }
        }

        stage('Apply') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'aws-creds',
                    usernameVariable: 'AWS_ACCESS_KEY_ID',
                    passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                )]) {
                    dir('terraform') {
                        sh """
                            export AWS_DEFAULT_REGION=ap-south-1
                            terraform apply \
                              -var-file=${params.environment}/${params.environment}.tfvars \
                              -var="app_version=${params.version}" \
                              -var="env=${params.environment}" \
                              -auto-approve
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'cleaning up workspace'
            // deleteDir()
        }
    }
}